// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.lp.dto;

import lombok.Data;

/**
 * @author 10263
 */
@Data
public class Message {
    //消息类型
    private Integer code;
    //额外信息
    private String message;
    //服务名
    private String serverName;
    //具体数据信息，一般用json包装
    private String data;
    //是否异步请求
    private Boolean async;

}
